services:
  emby-analytics:
    image: ghcr.io/themrclaus/emby-analytics:latest
    container_name: emby-analytics
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - emby_analytics_data:/var/lib/emby-analytics
    env_file:
      - .env

volumes:
  emby_analytics_data:
