run:
  timeout: 5m
  skip-dirs:
    - vendor/

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - govet
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - errcheck
    - goconst
    - stylecheck
    - unconvert
    - unparam

linters-settings:
  govet:
    check-shadowing: true
  stylecheck:
    checks: ["all", "-ST1000", "-ST1020", "-ST1021", "-ST1022"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst