name: Docker Publish

on:
  push:
    branches: [ main, '**' ]
    tags: [ 'v*', 'v*-*' ]
  release:
    types: [ published ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/TheMrClaus/emby-analytics

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=sha

      - name: Compute build vars and extra tags
        id: vars
        run: |
          sha_short=${GITHUB_SHA::7}
          date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            version="${GITHUB_REF_NAME}"
            if echo "$version" | grep -q -- '-'; then
              # pre-release tag (e.g., v1.2.3-beta.1)
              echo "extra_tags=${IMAGE_NAME}:beta" >> "$GITHUB_OUTPUT"
            else
              # stable tag
              echo "extra_tags=${IMAGE_NAME}:latest" >> "$GITHUB_OUTPUT"
            fi
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            version="main-${sha_short}"
            {
              echo "extra_tags<<EOF"
              echo "${IMAGE_NAME}:beta"
              echo "${IMAGE_NAME}:dev"
              echo "EOF"
            } >> "$GITHUB_OUTPUT"
          else
            version="${GITHUB_REF_NAME}-${sha_short}"
            echo "extra_tags=${IMAGE_NAME}:dev" >> "$GITHUB_OUTPUT"
          fi
          echo "sha_short=${sha_short}" >> "$GITHUB_OUTPUT"
          echo "date=${date}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ steps.vars.outputs.extra_tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_type == 'tag' && github.ref_name || steps.vars.outputs.version }}
            COMMIT=${{ steps.vars.outputs.sha_short }}
            DATE=${{ steps.vars.outputs.date }}
            REPO=TheMrClaus/emby-analytics
